spring:
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
    ds2:
      url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver